spring.application.name=Budget_Bounty
server.port=8081
# --- Oracle DB Connection ---
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/xe
spring.datasource.username=system
spring.datasource.password=ssn
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA / Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Hibernate 6 Dialect for Oracle ---
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.sql.init.mode=always
spring.datasource.initialization-mode=always